name: hello-world

on:
  push:
    branch:
      - main
  pull_request:
    branch:
      - main
  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
      - run: echo "lumanex fisrt pipeline yaml"
      - shell: bash

  goodbye:
    run-on: ubuntu:latest
    steps:
      - name: goodbye world
      - run: echo "good bye from lumanex"
      - shell: bash
